#ifndef BTTP_CONFIG
#define BTTP_CONFIG

#define NUM_STEPS 4
const uint8_t PINS[NUM_STEPS] = {A6, A7, A8, A9};
const uint8_t JOYSTICK_BUTTONS[NUM_STEPS] = {1, 2, 3, 4};
uint32_t thresholds[NUM_STEPS] = {300, 300, 300, 300};

#define BAUD_RATE 115200

#include "FastLED.h"
#define LED_TYPE WS2811
#define COLOR_ORDER BRG
#define NUM_LEDS_PER_STEP 20
#define NUM_LEDS NUM_LEDS_PER_STEP * NUM_STEPS
#define LED_DATA_PIN 3
#define UP_LED_INDEX 0
#define LEFT_LED_INDEX UP_LED_INDEX + NUM_LEDS_PER_STEP
#define DOWN_LED_INDEX LEFT_LED_INDEX + NUM_LEDS_PER_STEP
#define RIGHT_LED_INDEX DOWN_LED_INDEX + NUM_LEDS_PER_STEP
CRGBArray<NUM_LEDS> leds;
int led_indices[NUM_STEPS] = {LEFT_LED_INDEX, DOWN_LED_INDEX, UP_LED_INDEX, RIGHT_LED_INDEX};

#endif
